Repository 100-hours-a-week/10-team-joytas-dao-fe, pull requests merged in 2024-09, with the labels that each got.

#141 [수정] 마이룸, 오브제 관련 버그 해결
  src/pages/myRoom/MyRoom.tsx
  src/pages/objet/ObjetStyles.tsx
  src/pages/objet/newObjet/InputObjetInfo.tsx
  src/pages/user/UserDetail.tsx
Labels: 버그-일반

#175 오브제 음성통화 소리 관련 기능 추가
  src/components/call/Video.tsx
  src/components/call/VideoContainer.tsx
  src/components/call/VideoStyles.tsx
  src/pages/objet/ObjetCall.tsx
Labels: 기능 추가

#176 fix: 음성통화 진입 유저 이미지 매칭 에러 수정
  src/components/call/VideoContainer.tsx
Labels: 버그-일반

#190 refactor: 오브제 음성채팅 참가 예외처리 #187
  src/components/call/VideoContainer.tsx
Labels: 리팩토링

#194 [리팩토링] 오브제 생성/수정 코드 통합
  .eslintrc.cjs
  src/App.tsx
  src/components/objet/ObjetInputForm.tsx
  src/global/objetProps.tsx
  src/pages/objet/ObjetForm.tsx
  src/pages/objet/ObjetStyles.tsx
  src/pages/objet/UpdateObjet.tsx
  src/pages/objet/newObjet/NewObjet.tsx
  src/utils/validation.ts
Labels: 리팩토링

#200 fix: 음성채팅 참가 예외처리 버그 수정 #199
  src/components/call/VideoContainer.tsx
Labels: 버그-일반

#248 [리팩토링] 오브제 상세조회 리팩토링
  src/App.tsx
  src/pages/objet/Objet.tsx
  src/pages/objet/ObjetCall.tsx
  src/pages/objet/ObjetChatting.tsx
  src/pages/objet/ObjetDetail.tsx
  src/pages/objet/ObjetStyles.tsx
  src/utils/formatDatetime.tsx
  src/utils/objetContext.ts
Labels: 리팩토링
